name = "AccPhyHaissinski"
uuid = "0ee4d5d8-f1d6-4861-b7e4-fa5551b1b91e"
version = "1.0.0-DEV"
authors = ["Christian Ratcliff"]

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FHist = "68837c9b-b678-4cd5-9925-8a54edc8f695"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StochasticAD = "e4facb34-4f7e-4bec-b153-e122c37934ac"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[compat]
CairoMakie = "0.15.8"
Distributions = "0.25.123"
FFTW = "1.10.0"
FHist = "0.11.17"
Interpolations = "0.16.2"
LaTeXStrings = "1.4.0"
LinearAlgebra = "1.12.0"
LoopVectorization = "0.12.173"
ProgressMeter = "1.11.0"
Random = "1.11.0"
StaticArrays = "1.9.16"
Statistics = "1.11.1"
StochasticAD = "0.1.26"
StructArrays = "0.7.2"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
